### PR TITLE
Task

### PR DESCRIPTION
**Pull request by the-elves**
Hey,
This is the code for the task.
I guess qemu does not implement mailboxes.
I have checked the write mailbox message and am positive that it is correct.
But there is nor reply in the read mailbox register. Therefore I think qemu does not implement it.
Apart from that everything is put in place.

### CODE REVIEW

**Comment by boricj** [comment]
Hi,

The mailbox does work under QEMU. The issue is most likely due to the MMU, since it's activated at the end of the pre_init function. The kernel sees virtual addresses and the hardware sees physical addresses.

Either call the mailbox when the MMU hasn't been activated yet (inside pre_init), or map physical pages using kern_phys_map_ptr (check the rpi_serial.c file inside minix/kernel/arch/earm/bsp/rpi for an example). The first solution is easier since you don't have to juggle between virtual and physical addresses.

**Comment by the-elves** [comment]
Even after doing the mailbox calls from pre_init does not help. It does not return from readmailbox which is waiting for mailbox READ register to be written

**Comment by the-elves** [comment]
The task is complete. Kindly check

**Comment by the-elves** [comment]
Completely Working task is committed. 
Due to approaching deadline, some implementation is messy but I marked it in comments and will work on them later.
Thanks for your help

Ajinkya

**Comment by boricj** [comment]
No need to keep this open anymore since GSoC 2017 students are announced now.

**Pull request closed without merging**
